global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: pushgw
    scrape_interval: 1s
    static_configs:
      - targets: ['pushgw:9091']


